FROM nvidia/cuda:12.1.0-runtime-ubuntu18.04

COPY . .

ENV DEBIAN_FRONTEND=noninteractive

RUN --mount=type=cache,target=~/.cache/apt apt update
RUN --mount=type=cache,target=~/.cache/apt apt -y install python3.8
RUN --mount=type=cache,target=~/.cache/apt apt -y install python3-pip
RUN --mount=type=cache,target=~/.cache/apt apt -y install python3.8-venv
RUN --mount=type=cache,target=~/.cache/apt apt -y install make
RUN --mount=type=cache,target=~/.cache/apt apt -y install ffmpeg

RUN ln -s /usr/bin/python3.8 /usr/bin/python
RUN ln -s /usr/bin/pip3 /usr/bin/pip

RUN --mount=type=cache,target=~/.cache/app make clean venv

ENTRYPOINT ["make", "run"]

Hey Manan,

Hope you're doing great! I'm now open to new opportunities. Please feel free to share any available roles.

Best,
Vladimir

Hey Manan,

Sorry for the late reply. I'm now open to new opportunities. Please feel free to share any available roles.

Best,
Vladimir


I love how LLMs get all the hype, while old-school math models like Markov Chains and Shannon’s entropy just quietly do their thing.
1. GPT-4: "I simulate human reasoning."
Markov Chains: "Bro, I’ve been doing that since 1906."
2. Shannon (1948): "Text entropy helps predict words."
GPT-4 (2024): "Cool, but now they call me AI."

But let’s talk about something even more relevant—finding your next job. Here’s an approach that actually works.

ChatGPT Use Cases:
1. Product Analysis – ChatGPT excels at distilling marketing-heavy articles into concise insights. This is precisely what LLMs are designed for. Prompt: "URL insights." A good way to practice is by analyzing any crypto startup
2. Financial Data Analysis. Prompt: "All cash flow movements and stock buyback commitments for company X in 2024." Try this with Facebook as an example. I also recommend using Wolfram Alpha (there’s a dedicated economic analysis app) to improve financial intuition
3. Competitor Analysis – Prompt: "X competitors." You might need to take this list to a spreadsheet for further refinement. Helps anticipate strategic moves, as competitor behavior is highly interconnected.
4. Polishing Responses – The inverse of point #1: expanding and refining thoughts into well-articulated responses.
5. Interview Preparation – This one requires creativity. For example, gather background info, copy-paste participants profiles, and ask ChatGPT for the top 20 most likely questions (and answers lol).

LinkedIn Use Cases:
1. Candidate Competition Analysis (Requires premium) – You can check the number of applicants for a job posting. While not the exact number, it reflects candidate interest, let's call it temperature check. If it’s lower than usual, it’s worth digging into Glassdoor: what’s up with their management?
2. Assessing a Company’s Engineering Potential. Browse the list of engineers, check profiles, understand their tech stack and challenges. Recently, I saw a startup with Russian-Israeli roots claiming to be building a deepfake detector without having any significant engineering talent
3. Analyzing the Exec Team –I check the C-level and board members. If there’s no one with a physics or math background, that’s a potential red flag







Кейсы для ЧатГПТ:

1. Анализ продукта. ЧатГПТ хорошо справляется с "обезвоживанием" маркетинговых статей, это по сути то, в чем языковые модельки блистают по дизайну. Промт: "url инсайты"
2. Анализ конкурентов. Промт: "name конкуренты"
3. Полировка ответов. Тут тоже понятно, симметричная задача для первого пункта, когда нужно красиво развернуть мысль
4. Подготовка к этапам интервью. Тут творчески. Например, можно набросать контекст. Скопипастить профили участников и попросить топ 20 наиболее вероятных вопросов (и ответов лол)

Кейсы для линкедына:

1. Анализ конкуренции среди кандидатов (нужен премиyм). Можно смотреть количество откликов на вакансию. Понятное дело, что это не настоящее число, но оно отображает уровень интереса со стороны других кандидатов, этакую температуру. Если температура низкая по сранению с другими компаниями, то стоит покопать вглубь, а что у них там с менеджментом

2. Оценка инженерной культуры компании. Листаю список инженеров, открываю профили, понимаю, что за стэк и какие задачи

3. Анализ топов. Смотрю на C-левелов и совет директоров. Если среди них нет людей с физико-математическим образованием, это потенциальный красный флаг


-- Это может указывать на слабое понимание технологий и научного подхода в управлении


Есть ли техблог? Подробные ли статьи или там больше про маркетинг?


-- Проверять количество инженеров в компании как косвенный признак её технического уровня
-- Glassdoor, чтобы понять, как устроены процессы и есть ли жалобы на менеджмент

3. Анализ топов

-- Смотреть на C-level и совет директоров. Если среди них нет людей с физико-математическим образованием, это потенциальный красный флаг
-- Это может указывать на слабое понимание технологий и научного подхода в управлении