#FROM nvcr.io/nvidia/cuda:11.2.0-cudnn8-devel-ubuntu20.04
FROM nvcr.io/nvidia/cuda:12.1.0-devel-ubuntu18.04

#RUN apt update
#RUN apt install -y make
#RUN apt -y install build-essential
#RUN apt -y install python3.8
#RUN apt -y install python3-pip
#RUN apt -y install python3.8-venv

#RUN pip install eva-decord

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt -y install software-properties-common
RUN add-apt-repository ppa:jonathonf/ffmpeg-4 # for ubuntu20.04 official PPA is already version 4.2, you may skip this step
RUN apt update
RUN apt install -y build-essential python3-dev python3-setuptools make cmake
RUN apt install -y ffmpeg libavcodec-dev libavfilter-dev libavformat-dev libavutil-dev

RUN git clone --recursive https://github.com/dmlc/decord

RUN cd decord && mkdir build && cd build && cmake .. -DUSE_CUDA=0 -DCMAKE_BUILD_TYPE=Release && make